config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :users
  get "/users/:id/toggle_role/:role", to: "users#toggle_role"
  resources :blogs do
    resources :posts do
      member do
        get 'toggle_active'
        delete 'images/:img_id', to: 'posts#delete_img', as: 'delete_img'
      end
    end
  end
  resources :camps

  

  get 'accueil/index'

  root 'accueil#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :camp
  has_many :posts
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :need_admin, except: [:show, :update]
  before_action :need_moderator, only: [:show, :update, :edit]

  def need_admin
    redirect_to '/' unless current_user.is_admin?
  end

  def need_moderator
    redirect_to '/' unless current_user.has_role? :moderator, @blog.camp
  end

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all.includes(:camp)
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blogs_url = "http://blog.jabby.fr/"
    @posts = @blog.posts
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
    @camp_list = Camp.all.map{|c| [c.name, c.id]}
  end

  # GET /blogs/1/edit
  def edit
    @camp_list = Camp.all.map{|c| [c.name, c.id]}
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.where(id: params[:id]).includes({:posts =>:images}).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:url, :content, :name, :camp_id)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= bootstrap_form_for(@blog, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-8" ) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :url, label: "URL" %>
  <%= f.text_field :name, label: "Nom" %>
  <%= f.text_area :content, label: "Texte d'intro" %>
  <%= f.select :camp_id, @camp_list, { label: "Camp relié" } %>
  <%= f.form_group do %>
    <%= f.submit value: "Créer", class: "btn btn-default col-sm-4" %>
  <% end %>


<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Camp</th>
      <th>Url</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.name %></td>
        <td><%= blog.camp.name %></td>
        <td><%= blog.url %></td>
        <td>
          <%= link_to blog, class: "btn btn-default", title: "Voir" do %>
            <span class="glyphicon glyphicon-eye-open" ></span>
          <% end %>
          <%= link_to edit_blog_path(blog), class: "btn btn-default", title: "Editer" do %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>
          <%= link_to blog, method: :delete, data: { confirm: 'Etes-vous sûr ?' }, class: "btn btn-default", title: "Supprimer" do %>
            <span class="glyphicon glyphicon-trash"></span>          
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Ajouter', new_blog_path, class: "btn btn-default" %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<script>
  $(document).ready(function(){
    $(document).on('click', '.edit-thing', function(){
      var id = $(this).attr('name');
      $('#'+id).attr('readonly', false);
      $(this).toggleClass('edit-thing validate-thing');
      $(this).children('.glyphicon').toggleClass('glyphicon-pencil glyphicon-floppy-disk');
    });

    $(document).on('click', '.validate-thing', function(){
      var id = $(this).attr('name');
      $('#'+id).attr('readonly', true);
      if (id=="name"){
        var data = {name: $('#name').val()};
      }else{
        var data = {content: $('#content').val()};
      }
      var that = this;
      $.ajax({
        method: 'PATCH',
        url: '/blogs/<%= @blog.id%>.json',
        data: {blog: data }
      }).success(function(){
        $(that).toggleClass('edit-thing validate-thing');
        $(that).children('.glyphicon').toggleClass('glyphicon-pencil glyphicon-floppy-disk');
      });
    });

    $(".switch-actif").click(function(){
      var that = this;
      $.ajax({
        url: "/blogs/<%= @blog.id %>/posts/"+this.id+"/toggle_active",
      }).done(function() {
        $( that ).toggleClass( "glyphicon-check glyphicon-unchecked" );
      });
    });

  });
</script>

<div class="centered">
<p id="notice"><%= notice %></p>

<h1>Blog du camp <%= @blog.camp.name %></h1>

<div class="container-fluid spaced-rows">
  <div class="row">
    <label class="control-label col-sm-3 font-bold">URL du blog</label>
    <div class="col-sm-8">
      <input type="text" value="<%= @blogs_url%><%= @blog.url %>" class="form-control cursor-default" readonly>
    </div>
    <a class="col-sm-1 btn btn-default" href="<%= @blogs_url%><%= @blog.url %>" target="_blank">
      <span class="glyphicon glyphicon-eye-open"></span>
    </a>
  </div>

  <div class="row">
    <label class="control-label col-sm-3">Titre</label>
    <div class="col-sm-8">
      <input type="text" value="<%= @blog.name %>" id="name" class="form-control cursor-default" readonly>  
    </div>
    <a class="col-sm-1 btn btn-default edit-thing" name="name">
      <span class="glyphicon glyphicon-pencil"></span>
    </a>
  </div>

  <div class="row">
    <label class="control-label col-sm-3" for="blog_name">Texte d'introduction</label>
    <div class="col-sm-8">
      <textarea type="text" id="content" class="form-control cursor-default" rows="10" readonly ><%= @blog.content %></textarea>
    </div>
    <a class="col-sm-1 btn btn-default edit-thing" name="content">
      <span class="glyphicon glyphicon-pencil"></span>
    </a>
  </div>

  <h2>Liste des posts</h2>

  <table class="table">
    <thead>
      <tr>
        <th>Online</th>
        <th>Date</th>
        <th>Titre</th>
        <th>Images</th>
        <th>Vues</th>
        <th>Edition</th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td>
            <span id="<%= post.id %>" class="switch-actif glyphicon <%= post.active ? 'glyphicon-check' : 'glyphicon-unchecked' %> is-clickable"></span>
          </td>
          <td><%= post.date %></td>
          <td><%= post.title %></td>
          <td><%= post.images.length %></td>
          <td><%= post.views %></td>
          <td>
            <%= link_to edit_blog_post_path(@blog, post), class: "btn btn-default", title: "Editer" do %>
              <span class="glyphicon glyphicon-pencil"></span>
            <% end %>
            <% #= link_to blog_post_path(@blog, post), method: :delete, data: { confirm: 'Etes-vous sûr ?' }, class: "btn btn-default", title: "Supprimer" do %>
            <% #  <span class="glyphicon glyphicon-trash"></span> %>
            <% #end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to new_blog_post_path(@blog), class: "btn btn-default" do %>
    Nouveau post
  <% end %>


</div>
</div>