config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :users
  get "/users/:id/toggle_role/:role", to: "users#toggle_role"
  resources :blogs do
    resources :posts do
      member do
        get 'toggle_active'
        delete 'images/:img_id', to: 'posts#delete_img', as: 'delete_img'
      end
    end
  end
  resources :camps

  

  get 'accueil/index'

  root 'accueil#index'

end

app/models/camp.rb
class Camp < ActiveRecord::Base
  resourcify
end

app/controllers/camps_controller.rb
class CampsController < ApplicationController
  before_action :set_camp, only: [:show, :edit, :update, :destroy]
  before_action :need_admin, except: [:show, :update]
  before_action :need_moderator, only: [:show, :update, :edit]

  def need_admin
    redirect_to '/' unless current_user.is_admin?
  end

  def need_moderator
    redirect_to '/' unless current_user.has_role? :moderator, @camp
  end

  # GET /camps
  # GET /camps.json
  def index
    @camps = Camp.all
  end

  # GET /camps/1
  # GET /camps/1.json
  def show
  end

  # GET /camps/new
  def new
    @camp = Camp.new
  end

  # GET /camps/1/edit
  def edit
  end

  # POST /camps
  # POST /camps.json
  def create
    @camp = Camp.new(camp_params)

    respond_to do |format|
      if @camp.save
        format.html { redirect_to @camp, notice: 'Camp was successfully created.' }
        format.json { render :show, status: :created, location: @camp }
      else
        format.html { render :new }
        format.json { render json: @camp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /camps/1
  # PATCH/PUT /camps/1.json
  def update
    respond_to do |format|
      if @camp.update(camp_params)
        format.html { redirect_to @camp, notice: 'Camp was successfully updated.' }
        format.json { render :show, status: :ok, location: @camp }
      else
        format.html { render :edit }
        format.json { render json: @camp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /camps/1
  # DELETE /camps/1.json
  def destroy
    @camp.destroy
    respond_to do |format|
      format.html { redirect_to camps_url, notice: 'Camp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_camp
      @camp = Camp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def camp_params
      params.require(:camp).permit(:name, :start_date, :end_date, :location)
    end
end

app/helpers/camps_helper.rb
module CampsHelper
end

app/views/camps/_form.html.erb
<%= bootstrap_form_for(@camp, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-8" ) do |f| %>
  <% if @camp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@camp.errors.count, "error") %> prohibited this camp from being saved:</h2>

      <ul>
      <% @camp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :name, label: "Nom" %>
  <%= f.text_field :start_date, label: "Début" %>
  <%= f.text_field :end_date, label: "Fin" %>
  <%= f.text_field :location, label: "Lieu" %>
  <%= f.form_group do %>
    <%= f.submit value: "Créer", class: "btn btn-default col-sm-4" %>
  <% end %>

<% end %>

app/views/camps/edit.html.erb
<%= link_to 'Retour à la liste', camps_path %>

<h1>Editer un camp</h1>

<%= render 'form' %>

app/views/camps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Camps</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Dates</th>
      <th>Lieu</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @camps.each do |camp| %>
      <tr>
        <td><%= camp.name %></td>
        <td>Du <%= camp.start_date %> au <%= camp.end_date %></td>
        <td><%= camp.location %></td>
        <td>
          <%= link_to camp, class: "btn btn-default", title: "Voir" do %>
            <span class="glyphicon glyphicon-eye-open" ></span>
          <% end %>
          <%= link_to edit_camp_path(camp), class: "btn btn-default", title: "Editer" do %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>
          <%= link_to camp, method: :delete, data: { confirm: 'Etes-vous sûr ?' }, class: "btn btn-default", title: "Supprimer" do %>
            <span class="glyphicon glyphicon-trash"></span>          
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Ajouter', new_camp_path, class: "btn btn-default" %>

app/views/camps/new.html.erb
<%= link_to 'Retour à la liste', camps_path %>

<h1>Nouveau Camp</h1>

<%= render 'form' %>

app/views/camps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @camp.name %>
</p>

<p>
  <strong>Date:</strong>
  Du <%= @camp.start_date %> au <%= @camp.end_date %>
</p>

<p>
  <strong>Lieu:</strong>
  <%= @camp.location %>
</p>

<%= link_to 'Edit', edit_camp_path(@camp) %> |
<%= link_to 'Back', camps_path %>